### ISSUE TITLE
Reference asset pipeline in cms-css

### ISSUE THREAD

**Issue by kylebolstad** [comfy/comfortable-mexican-sofa#153]
Is it possible to reference the asset pipeline in the CSS included in the 'cms-css' directory? Adding a css.css.erb or css.css.scss file to the cms_fixtures doesn't seem to get imported. 

POSSIBLE USES

image-url("rails.png") becomes url(/assets/rails.png)
.class { background-image: url(<%= asset_path 'image.png' %>) }

**Comment by milgner** [comment]
This behaviour is only applicable to development mode (I'm really really surprised that it worked for you in Rails 3.2): in production mode, once the assets are compiled, they should be served from `public/assets` where they have the digests appended to their original names. The webserver cannot possibly know to serve them without the real filename.

Running generated CSS through the asset pipeline seems like a really good idea. Otherwise things like described in the original issue will not work.
