### ISSUE TITLE
Redactor cleaning tags

### ISSUE THREAD

**Issue by Ch1mpooya** [comfy/comfortable-mexican-sofa#697]
There's a function that messes up / cleans  everything I write in html mode.

How can I turn if off please?

**Comment by GBH** [comment]
Most of wysiwyg editors clean html tags out. Redactor is not an exception. I vaguely remember there was a setting for it to allow some html entities in. Actually here's a related issue: https://github.com/comfy/comfortable-mexican-sofa/issues/609

When you create layouts/pages in CMS, it actually doesn't create template files.

Page titles can be handled via field tags: https://github.com/comfy/comfortable-mexican-sofa/wiki/Tags#field

**Comment by Rubyum** [comment]
thanks. 

https://imperavi.com/redactor/docs/settings/clean/#setting-replaceDivs
it's empty. 

So Comfy's  editor name is Redactor? I thought it's a paid more advanced version that you need to install first. Because there's a tutorial on how to switch to Redactor editor.

Regarding to my my first question:
1> Layouts, When I put a code either to CSS or JS section, nothing happens. Only when I put it to application.css/js. 
do you know why?

what about that? 


Why there's no chat room on gitter or IRC? What about to create one?
