### ISSUE TITLE
CMS tags not rendering

### ISSUE THREAD

**Issue by AdnanTheExcellent** [comfy/comfortable-mexican-sofa#712]
I am having a weird problem where, after upgrading to version 1.12.8, my CMS tags no longer render. The tags just show up as text in my html. Screenshot below is provided of a cms snippet being rendered with a partial tag that doesn't render properly:

![cms tags](https://cloud.githubusercontent.com/assets/943069/14024870/98109f54-f1a8-11e5-8222-d391ede7c9b6.png)

Any idea why this is happening and how to fix this?

**Comment by montooner** [comment]
I discussed this with @AdnanTheExcellent offline. 

Found the issue:  

1. Change use of `cms_snippet_content` to `cms_snippet_render`, in the ERB
  - Was previously using `cms_snippet_content` ([cms_helper.rb](https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/helpers/comfy/cms_helper.rb#L21)), which does not expand the cms tag
  - Use `cms_snippet_render` ([cms_helper.rb](https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/helpers/comfy/cms_helper.rb#L42)) instead
2. After the change, we discovered that `cms_snippet_render` was rendering an empty string
  - `cms_snippet_render` returns an empty string when `cms_site` and `@cms_site` are both nil ([cms_helper.rb:L43](https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/helpers/comfy/cms_helper.rb#L43))
   - I found it inunusual that `cms_snippet_render`'s decides to render an empty string when cms_site is empty, because `cms_snippet_content` will will actually retrieve the cms_site instead of returning an empty string

The solution:


    # Add a before_filter in the controller loading the page
    # Alternately, you could overwrite cms_snippet_render with new behavior

    before_filter :load_cms_site

    def load_cms_site
      # The following is copied from cms_snippet_content
      host, path = request.host_with_port.downcase, request.fullpath if respond_to?(:request) && request
      @cms_site = Comfy::Cms::Site.find_site(host, path)
    end
