### ISSUE TITLE
Confused about Redactor

### ISSUE THREAD

**Issue by JohnSmall** [comfy/comfortable-mexican-sofa#713]
I'm using 1.12.9, the latest at time of writing. I found the wysiwyg editor on text areas wasn't working. As I'd previously used an earlier version of Comfy in another project with CodeMirror, I decided that rather than muck around getting CodeMirror to work I'd go straight to Redactor. So I bought it as recommended in the Wiki and followed the instructions on [/Replacing-default-wysiwyg-editor-with-redactor](https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-redactor), ignoring the bit about 'Use version 1.12.2 of Comfortable Mexican Sofa', because I thought I could tweak things a bit to get the code working with 1.12.9. But....

It doesn't work. Not only doesn't it work, but it seems that Redactor is already included in 1.12.9, but in a way that makes it non-functioning. Which prompts these questions;-

1.  If Redactor is already included in 1.12.9, why does the page 'Replacing default wysiwyg editor with redactor' not say 'just use 1.12.9 because Redactor is included', instead of 'Download Redactor: etc' I've just paid for Redactor, and it's already included in Comfy
 
3. Why does the page [Customizing the WYSIWYG Editor](https://github.com/comfy/comfortable-mexican-sofa/wiki/Customizing-the-WYSIWYG-Editor) talk about "Getting the WYSIWYG (Redactor) to not add paragraph on new lines" and then at the bottom of the page say "Replacing-default-wysiwyg-editor-with-redactor"

5. Why doesn't Redactor work in 1.12.9? I see all the asset files loaded, but the buttons don't appear on the text areas. Which leaves me with a CMS that doesn't have a wysiwyg editor for text areas. I.e. 1.12.9 is non-functional out of the box.
 
7.  Why do I still see stuff for CodeMirror in the HTML source e.g.

    <script src="/assets/codemirror.self etc

It looks like 1.12.9 is in the process of being moved from CodeMirror to Redactor, but left in a part completed state so that neither CodeMirror nor Redactor work. Also the Wiki is in a half finished state so that the help pages talk about Redactor as if it's the default wysiwyg editor and on the same pages talk about replacing the default editor with Redactor. 

Also, standard semantic versioning practice. Minor bug fixes increment the last number, so the change from 1.12.2 to 1.12.9 should have been just a minor bug fix. But it seems to be an entirely new feature, so the version should be 1.13.0, or as it's a breaking change 2.0.0

WTF is going on? Why doesn't the WYSIWYG editor work and why does the Wiki recommend buying Redactor if it's already included in Comfy?

**Comment by GBH** [comment]
1.12.9 is bundled with Redactor 10.2.5. You don't need to do anything special other than use rich_text tags: `{{ cms:page:content:rich_text }}`

Imperavi now released Redactor II that I cannot bundle anymore because my OEM license is no good for this version bump. They want $1500 now, compared to old $500 that's a tad too much. So if you're trying to integrate new Redator, you're on your own here.

CodeMirror is not the same as Redactor. It's used for HTML highlighting mostly. It's not a rich-text editor.

**Comment by mattmueller** [comment]
I have added further instructions for getting Redactor II to work with >= 1.12.9 here for those that may need it: https://github.com/comfy/comfortable-mexican-sofa/wiki/Integrating-Redactor-II-With-Comfy--1.12.9-or-Later

**Comment by sapraaman** [comment]
Hi @mattmueller , the instructions do not seem to work. I am using latest CMS and purchased redactor to integrate. After following all the instructions, the default toolbar is not coming up properly. Please see https://screencast.com/t/TvunICBTtMev. See the missing B/I buttons in toolbar, also "Format" button is missing​. Dropdown menu on clicking "Link" shows empty menu item instead of "Insert Link".

Any thoughts ? Am I missing something ?

**Comment by realCh4mp** [comment]
this wysiwyg editor is bad, please replace with tinyMCE asap, thanks!
